### ISSUE TITLE
Gamepad error, interact doesnt work

### ISSUE THREAD

**Issue by smalltinypp** [ZioPao/The-Only-Cure#147]
Interact button does not work with gamepads. I click interact, error message appears. Interact works with mkb.

[18-10-24_19-26-30_DebugLog.txt](https://github.com/user-attachments/files/17441725/18-10-24_19-26-30_DebugLog.txt)

**Comment by Mork29** [comment]
I have a similar issue. Whenever I try to access the single context menu (square/X) nothing happens and I get an error

**Comment by IvanKMZ** [comment]
I have the same problem after update

**Comment by Mork29** [comment]
```attempted index: getOptionFromName of non-table: true
function: createMenu -- file: LimitActionsController.lua line # 296 | MOD: The Only Cure
function: createMenu -- file: ISMenuContextWorld.lua line # 53 | Vanilla
function: createWorldMenu -- file: ISContextManager.lua line # 28 | Vanilla
function: getXButtonObjects -- file: ISButtonPrompt.lua line # 990 | Vanilla
function: interact -- file: ISButtonPrompt.lua line # 182 | Vanilla
function: onXPress -- file: ISButtonPrompt.lua line # 1048 | Vanilla
function: onPressButtonNoFocus -- file: JoyPadSetup.lua line # 305 | Vanilla
function: onPressButton -- file: JoyPadSetup.lua line # 329 | Vanilla
function: update -- file: JoyPadSetup.lua line # 779 | Vanilla
function: onJoypadRenderTick -- file: JoyPadSetup.lua line # 796 | Vanilla
java.lang.RuntimeException: attempted index: getOptionFromName of non-table: true
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:65)
    at zombie.GameWindow.frameStep(GameWindow.java:778)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by ZioPao** [comment]
Hi, controllers aren't supported with this mod.
I've "fixed" this behavior and will push the updated version soon. Keep in mind that some little things may not work correctly and I won't spend too much time in trying to fix unintended behaviors when using controllers.

I'll keep this open to receive feedback about this fix in particular.

**Comment by Mork29** [comment]
Hi thanks for the response! Any reason in particular that supporting controllers is an issue? The mod has worked perfectly for me so far. Just curiosity more than anything. Thanks for your work!

**Comment by ZioPao** [comment]
> Hi thanks for the response! Any reason in particular that supporting controllers is an issue? The mod has worked perfectly for me so far. Just curiosity more than anything. Thanks for your work!

A lot of things in Zomboid are tacked on in a fairly janky way. 
Controller support is too. The main issue is connected to the handling of the context menu that appears when you right click. Some modifications are made to that:
- Fix a broken behavior with broken glass when you're missing a right hand
- Disabling various options when you don't have both hands.

At the moment, the fix I pushed is just to disable these modifications when controllers are in use.


This bug was actually in for a very long time, but seems like it was hidden beneath the fact that nobody actually used a controller + double amputations and no prosthetics 😆.

**Comment by Mork29** [comment]
thanks for the explanation... I have not amputated anything as yet but was still getting the error regardless

**Comment by ZioPao** [comment]
> thanks for the explanation... I have not amputated anything as yet but was still getting the error regardless

That's because I've added a fix for the broken glass behavior in the last update, which has the checks for the amputations only after the bug is already triggered.

**Comment by Mork29** [comment]
aha i see, thanks again for explaining, and your patience

**Comment by Mork29** [comment]
The 'fix' is working! Thanks for the help
